Repository tensorflow/tfx, pull requests merged in 2019-04, with the labels that each got.

#29 Fix references to examples after moving these to tfx/examples
  README.md
  docs/tutorials/_toc.yaml
  tfx/examples/chicago_taxi/README.md
Labels: cla: yes

#36 Update .gitignore
  .gitignore
Labels: cla: yes, ready to pull

#30 Lock in version of `kfp`
  setup.py
Labels: cla: yes

#27 Replace tf.sparse_to_dense with tf.SparseTensor and tf.sparse.to_dense
  docs/tutorials/transform/census.ipynb
  tfx/components/testdata/module_file/transform_module.py
  tfx/examples/chicago_taxi/preprocess.py
  tfx/examples/chicago_taxi_pipeline/taxi_utils.py
Labels: cla: yes

#39 Orchestration/Kubeflow - Removed the use of undocumented KFP compiler API
  tfx/orchestration/kubeflow/runner.py
Labels: cla: yes

#50 Tiny typo
  tfx/utils/types.py
Labels: cla: yes

#52 Document new pending PRs in CONTRIBUTING.md
  tfx/CONTRIBUTING.md
Labels: cla: no

#55 Fix for github issue #45: num_steps=None is replaced by num_steps=0 by trainer_pb2.py; later, TF raises an error as num_steps must be None or >0.
  tfx/components/trainer/executor.py
Labels: cla: no

#53 Addressing issue #43: Fix a caching bug that prevents new run.
  tfx/orchestration/metadata.py
  tfx/orchestration/metadata_test.py
Labels: cla: no

#60 Prepare for 0.13 release.
  README.md
  RELEASE.md
  setup.py
Labels: cla: no

#61 Partially rollback example code and restore usage of PipelineOperator. since documentation still instructs not to use the deprecated version.
  tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow.py
  tfx/examples/chicago_taxi_pipeline/taxi_pipeline_simple.py
Labels: cla: no

#62 Update release note to prepare for 0.13.0 release.
  RELEASE.md
Labels: cla: no

#63 Correct release doc typo.
  RELEASE.md
Labels: cla: no

#65 Fix for executor class flag reference. This script was dormant and not used by any automated test yet, but keeping it fixed in case manually invoked by someone.
  tfx/scripts/run_executor.py
  tfx/scripts/run_executor_test.py
Labels: cla: no

#66 Prepare for 0.13.0rc1 release, fixing run_executor script.
  RELEASE.md
  setup.py
  tfx/version.py
Labels: cla: no

#67 Simplifies dependencies in TFX workshop tutorial requirements.txt.
  tfx/examples/workshop/notebooks/requirements.txt
  tfx/examples/workshop/notebooks/step3.ipynb
  tfx/examples/workshop/notebooks/step6.ipynb
  tfx/examples/workshop/notebooks/tfx_utils.py
  tfx/examples/workshop/notebooks/utils.py
Labels: cla: no

#48 Fix Chicago Taxi Example not working on Dataflow
  tfx/examples/chicago_taxi/preprocess.py
  tfx/examples/chicago_taxi/process_tfma.py
  tfx/examples/chicago_taxi/tfdv_analyze_and_validate.py
Labels: cla: yes

#70 PR #48: Fix Chicago Taxi Example not working on Dataflow
  RELEASE.md
  tfx/examples/chicago_taxi/preprocess.py
  tfx/examples/chicago_taxi/process_tfma.py
  tfx/examples/chicago_taxi/tfdv_analyze_and_validate.py
Labels: cla: no

#75 Update TFX Workshop example files README
  tfx/examples/workshop/README.md
Labels: cla: no
